var numero = 0;
var string = " Cascata Guarani - 121";
var  precoDoEtanol= 4.30;
var luzDaLampada ="acessa";
var endereco = 2138387467;
var digitoElevador = 7;
var luzElevador ="picando";
var dataDeAniversario = 09/02/2020;
var pesoDoPrato = 2.0;
var numeroDeBois = 29;
var diaDaPascoa= 17/04/2020;
var numeroDeLaranjas= 2;
var vogalMinuscula = "a" 
var tituloLivro = " romeu ";
var limiteCartao= 42;
var horaDoJogo= 17.10;
var alturaDoPredio = 12.23;
var paginasDoCaderno= 8;
var salaReuniao = "ocupada";
var alternativas= 4;



